### ISSUE TITLE
[Feature] Add support for the GitHub's V4 `upload-artifact` and `download-artifact` actions.

### ISSUE THREAD

**Issue by spkane** [xSAVIKx/artifact-exists-action#10]
**What**

Add support for the GitHub's V4 `upload-artifact` and `download-artifact` actions.

---

**Why**

We want to upgrade to the newer v4 GitHub actions primarily to avoid the deprecation warnings when workflows are run, but we can not because we rely on this action for a critical part of our workflow.

---

cc/ @manidharanupoju24 @akbar-mohammad

**Comment by xSAVIKx** [comment]
Hey @spkane. Thx for opening the issue. I'll gladly accept a PR with the required changes if you're up to working on it.

The v4 version of the artifact actions have significantly redesigned API and approach overall. This basically makes it impossible to support both v1-3 and v4 actions together.

**Comment by spkane** [comment]
@xSAVIKx - Do you think it would make more sense to create a "new" action via a fork of this repo that does this same thing but for the newer v4+ workflows? At some point, I am assuming that the older v3 versions are going to be fully deprecated.

**Comment by xSAVIKx** [comment]
I guess it can just be a v2 of this action, but the main part is to rework completely the API layer and logic.

**Comment by soderlind** [comment]
> I guess it can just be a v2 of this action, but the main part is to rework completely the API layer and logic.

@xSAVIKx May I suggest `v4` to sync with v4 in upload-artifact and download-artifact? :)

**Comment by xSAVIKx** [comment]
It's actually gonna be a sync with the [artifacts API](https://github.com/actions/toolkit/tree/main/packages/artifact). The upload/download actions v1-3 work on artifact v1 API and v4 versions work on artifacts v2 API

**Comment by soderlind** [comment]
It would also be very nice if you added support for checking if an artifact exists outside the workflow. `download-artifact@4` [can](https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories):

```yaml
– name: Download Artifact
  uses: actions/download-artifact@v4
  with:
    # name: [artifact name] # If specified, files will be extracted to the root folder!
    github-token: ${{ secrets.GITHUB_TOKEN }}
    run-id: ${{ github.event.workflow_run.id }}

```
