### ISSUE TITLE
`set-output` deprecation warning

### ISSUE THREAD

**Issue by Jrc356** [xSAVIKx/artifact-exists-action#3]
When using the action, a warning pops up that `set-output` is deprecated and will be fully disabled on May 31st, 2023

Screenshot of warning:

![Screen Shot 2022-12-08 at 12 08 11 PM](https://user-images.githubusercontent.com/37387479/206517804-fd56c879-4cc1-4cba-ac73-d8d520a95bd6.png)

**Comment by xSAVIKx** [comment]
Thank you for opening the issue! I'd take a look as soon as I have some extra time.

You can open a PR with a fix if you're willing to 🙂 contributions are very welcome

**Comment by Jrc356** [comment]
> Thank you for opening the issue! I'd take a look as soon as I have some extra time.
> 
> You can open a PR with a fix if you're willing to 🙂 contributions are very welcome

I'll see what I can do! I suspect it might be as simple as bumping the library version. I'll try taking a look tonight 👍

**Comment by Jrc356** [comment]
hmmm.... looks like that didn't do it, I'm still getting the deprecation warning when using `v0`

**Comment by xSAVIKx** [comment]
> hmmm.... looks like that didn't do it, I'm still getting the deprecation warning when using `v0`

Try referencing v0.2. I may have fcked up the versioning a bit 🙂
But if this won't help, I'll go over it during the weekend

**Comment by Jrc356** [comment]
Will give it a shot, I was referencing `v0` as I thought that would reference `v0.2` but try explicitly referencing `v0.2` and report back

**Comment by Jrc356** [comment]
ah interesting, so using the following worked:

```yml
- name: Verify coverage
        id: coverage
        uses: xSAVIKx/artifact-exists-action@v0.2
```

when I tried the following I still got the issue:
```yml
- name: Verify coverage
        id: coverage
        uses: xSAVIKx/artifact-exists-action@v0
```
