### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by titouancreach** [xSAVIKx/artifact-exists-action#9]
Hello, I noticed my CI stopped working. After some invests, `xSAVIKx/artifact-exists-action@v0` reports that artifact is missing even if it's present. (and before it worked and didn't touch CI since months.

  
<img width="1073" alt="Capture d’écran 2024-01-03 à 15 12 00" src="https://github.com/xSAVIKx/artifact-exists-action/assets/3995719/89bfd994-e374-4495-ba20-4de500d89240">

<img width="1017" alt="Capture d’écran 2024-01-03 à 15 13 12" src="https://github.com/xSAVIKx/artifact-exists-action/assets/3995719/ad179e6c-af22-4ee9-8a33-1e77f64e5647">

I'm not sure but it look likes it's due to the last commits.
I can help if you want to speed up the process 👍 

Thanks

**Comment by titouancreach** [comment]
I investigated a little more:
  - On your tests (https://github.com/xSAVIKx/artifact-exists-action/actions/runs/7389304539/job/20101846455) we can notice:

```
Run ./
Starting download for test-workflow. Temporary storing at artifactExistsYBpIkm/test-workflow if exists.
Artifact test-workflow does not exist.
```

if `Artifact test-workflow does not exist.` has been printed, then: it means a exception has been raised here (https://github.com/xSAVIKx/artifact-exists-action/blob/master/index.js#L20) and we set "results" to false. 

This means that:

```yaml
- name: "Echo if artifact exists"
        run: echo "::notice::Artifact in-deed exists."
        if: "${{ steps.check_workflow_exists.outputs.exists }}"
```

shouldn't been executed (but it is). I think of a  "truthy falsy syntax bash mess" where == 'true' is required.

**Comment by xSAVIKx** [comment]
Hey @titouancreach, thx for reporting this. I'm trying to hack this quickly. If I won't you may fixate the action version to `v0.2` or maybe I'll restore the `v0` tag to the `v0.2` a bit later today.

**Comment by titouancreach** [comment]
Thanks for your help, don't hesitate if there is anything I can do !

**Comment by xSAVIKx** [comment]
@titouancreach can you please try it out now? I've changed the v0 pointer and basically rolled back the recent migration to v2 `artifact` API as it changes a lot of things.

Also only `v1-v3` upload actions are supported

**Comment by titouancreach** [comment]
I just did and it fails with the same messages / error. I suspect github to have a cache.

**Comment by xSAVIKx** [comment]
What upload-artifact version are you using?

**Comment by titouancreach** [comment]
@xSAVIKx  actions/upload-artifact@v3

**Comment by snojcb** [comment]
This action is broken for me as well.  I reverted back to v0.2, and is working again.

**Comment by snojcb** [comment]
If it helps, here is how I'm using this action.  One shared workflow uploads artifacts:

```
    - name: Preserve Built Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: local-artifacts
        path: |
          dist/${{ inputs.subproject-name }}-*.jar
        retention-days: 1
```

and another shared workflow will check if the artifact exists, and download it if the artifact does exist:

```
    - name: Check for Local Artifacts
      uses: xSAVIKx/artifact-exists-action@v0.2
      id: "check-local-artifacts"
      with:
        name: 'local-artifacts'

    - name: Fetch Local Artifact
      if: ${{ steps.check-local-artifacts.outputs.exists == 'true' }}
      env:
        ARTIFACT_EXISTS: ${{ steps.check-local-artifacts.outputs.exists }}
      uses: actions/download-artifact@v3
      with:
        name: local-artifacts
        path: dist
```
